apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.adsService.service.type }}
  selector:
    app: adservice
  ports:
  - name: {{ .Values.adsService.service.name }}
    port: {{ .Values.adsService.service.port }}
    targetPort: {{ .Values.adsService.ports.containerPort }}
