apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.cartService.service.type }}
  selector:
    app: cartservice
  ports:
  - name: {{ .Values.cartService.service.name }}
    port: {{ .Values.cartService.service.port }}
    targetPort: {{ .Values.cartService.ports.containerPort }}