apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.checkoutService.service.type }}
  selector:
    app: checkoutservice
  ports:
  - name: {{ .Values.checkoutService.service.name }}
    port: {{ .Values.checkoutService.service.port }}
    targetPort: {{ .Values.checkoutService.ports.containerPort }}