apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-cartservice
spec:
  host: {{ printf "cartservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-productcatalogservice
spec:
  host: {{ printf "productcatalogservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-currencyservice
spec:
  host: {{ printf "currencyservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-paymentservice
spec:
  host: {{ printf "paymentservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-shippingservice
spec:
  host: {{ printf "shippingservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-emailservice
spec:
  host: {{ printf "emailservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-checkoutservice
spec:
  host: {{ printf "checkoutservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-recommendationservice
spec:
  host: {{ printf "recommendationservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
--- 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-adservice
spec:
  host: {{ printf "adservice.%s.svc.cluster.local" .Release.Name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
