apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  hosts:
  - {{ printf "frontend.%s.svc.cluster.local" .Release.Name }}
  http:
  - route:
    - destination:
        host: {{ printf "frontend.%s.svc.cluster.local" .Release.Name }}
        port:
          number: 80