apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.shippingService.service.type }}
  selector:
    app: shippingservice
  ports:
  - name: {{ .Values.shippingService.service.name }}
    port: {{ .Values.shippingService.service.port }}
    targetPort: {{ .Values.shippingService.ports.containerPort }}