apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.shippingService.service.type }}
  selector:
    app: shippingservice
  ports:
  - name: {{ .Values.shippingService.service.name }}
    port: {{ .Values.shippingService.service.port }}
    targetPort: {{ .Values.shippingService.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.redisCart.service.type }}
  selector:
    app: redis-cart
  ports:
  - name: {{ .Values.redisCart.service.name }}
    port: {{ .Values.redisCart.service.port }}
    targetPort: {{ .Values.redisCart.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.adsService.service.type }}
  selector:
    app: adservice
  ports:
  - name: {{ .Values.adsService.service.name }}
    port: {{ .Values.adsService.service.port }}
    targetPort: {{ .Values.adsService.ports.containerPort }}
